local-phone-apps = $(private-phone-apps)

private-phone-apps := ApplicationsProvider \
					    BackupRestoreConfirmation \
					    Apollo.apk \
						ApplicationsProvider.apk \
						BackupRestoreConfirmation.apk \
						Bluetooth.apk \
						Browser.apk \
						Calculator.apk \ 
						Calendar.apk \   
						CalendarProvider.apk \           
						CertInstaller.apk \  
						CMFileManager.apk \  
						CMFileManagerThemes.apk \        
						CMUpdater.apk \  
						CMWallpapers.apk \   
						CMWimaxSettings.apk \
						Contacts.apk \   
						ContactsProvider.apk \           
						DefaultContainerService.apk \    
						DeskClock.apk \  
						Development.apk \
						DownloadProvider.apk \           
						DownloadProviderUi.apk \         
						DrmProvider.apk \
						DSPManager.apk \ 
						Email.apk \  
						Exchange2.apk \  
						FmRadioReceiver.apk \
						Galaxy4.apk \
						Gallery2.apk \   
						HoloSpiralWallpaper.apk \        
						HTMLViewer.apk \ 
						InputDevices.apk \   
						KeyChain.apk \   
						LatinIME.apk \
						LiveWallpapers.apk \
						LiveWallpapersPicker.apk \
						MagicSmokeWallpapers.apk \
						MediaProvider.apk \
						Mms.apk \
						NoiseField.apk \
						PackageInstaller.apk \
						PhaseBeam.apk \
						Phone.apk \
						PicoTts.apk \
						Provision.apk \
						QuickSearchBox.apk \
						Settings.apk \
						SettingsProvider.apk \
						SharedStorageBackup.apk \
						SoundRecorder.apk \
						SpareParts.apk \
						Superuser.apk \
						SystemUI.apk \
						TelephonyProvider.apk \
						Term.apk \
						ThemeChooser.apk \
						ThemeManager.apk \
						Torch.apk \
						Trebuchet.apk \
						UserDictionaryProvider.apk \
						VideoEditor.apk \
						VisualizationWallpapers.apk \
						VoiceDialer.apk \
						VpnDialogs.apk \
						WAPPushManager.apk 
#CMB!